# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VueWiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadmodel',
            options={'managed': True},
        ),
    ]
