# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VueWiz', '0002_auto_20180414_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
