# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VueWiz', '0003_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='title',
            field=models.CharField(blank=True, db_column=b'title', help_text=b'Title of the image', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='pdfFile',
            field=models.FileField(blank=True, db_column=b'pdffile', help_text=b'Load a pdf.', null=True, upload_to=b'media'),
        ),
    ]
