# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-15 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VueWiz', '0005_auto_20180415_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadmodel',
            options={},
        ),
    ]
