# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VueWiz', '0007_auto_20180415_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column=b'title', help_text=b'Title of the image', max_length=180, null=True)),
                ('file', models.FileField(blank=True, db_column=b'file', help_text=b'Load a resume.', null=True, upload_to=b'media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column=b'title', help_text=b'Title of the video', max_length=180, null=True)),
                ('file', models.FileField(blank=True, db_column=b'file', help_text=b'Load a video.', null=True, upload_to=b'media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='uploadModel',
        ),
    ]
